### ISSUE TITLE
Any way to move captions outside of the container and keep synched?

### ISSUE THREAD

**Issue by jackmcdade** [nathansearles/slidesjs#41]
Hey there, love the plugin. I'm hoping i can use it for a project i'm on, but i need to show the captions _outside_ the main slider container (e.g. in a sidebar). Are there any easy methods to do this? CSS alone won't work because of the necessary overflow:hidden, and using callbacks won't guarantee that the captions are synced with their appropriate parent image.

Any ideas, or should i move on to another plugin altogether?

**Comment by sfregolina** [comment]
Hi,

I'm trying to do something very similar.

Have you solved this problem?

Thanks!
